;/* This is auto-generated ASM code from LDmicro. Do not edit this file!
;   Go back to the LDmicro ladder diagram source for changes in the ladder logic. */
;Atmel AVR ATmega328 28-PDIP is the LDmicro target processor.
.DEVICE ATmega328
;#pragma AVRPART ADMIN PART_NAME ATmega328
;.INCLUDE <m328def.inc>
.CSEG
.ORG 0x0
;TABSIZE = 8
