/* This is auto-generated C header from LDmicro. Do not edit this file!
   Go back to the LDmicro ladder diagram source for changes in the ladder logic,
   and make any C additions in additional .c or .h files linked against this one. */
#ifndef __trial1_H__
#define __trial1_H__

#include "ladder.h"

// PLC cycle interval, set this according to LDmicro settings. (micro seconds)
#define PLC_INTERVAL 10000 // us

#ifdef USE_WDT
  #include <avr\wdt.h>
#endif
extern void loopPlc(void);  // Call loopPlc() function in loop() of your arduino project
extern void setupPlc(void); //  or initialize PLC cycle timer in this function
extern void PlcCycle(void); //  and call PlcCycle() function once per PLC cycle timer.

// You provide I/O pin mapping for ARDUINO in ladder.h.
// See example lader.h_.

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_rung_top;
#endif
#define Read_Ib_rung_top() Ib_rung_top
#define Write_Ib_rung_top(x) (Ib_rung_top = x)
#define Write0_Ib_rung_top() (Ib_rung_top = 0)
#define Write1_Ib_rung_top() (Ib_rung_top = 1)

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XPB1() digitalRead(pin_Ub_XPB1)
  #else
    PROTO(ldBOOL Read_Ub_XPB1(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parOut_0;
#endif
#define Read_Ib_parOut_0() Ib_parOut_0
#define Write_Ib_parOut_0(x) (Ib_parOut_0 = x)
#define Write0_Ib_parOut_0() (Ib_parOut_0 = 0)
#define Write1_Ib_parOut_0() (Ib_parOut_0 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parThis_0;
#endif
#define Read_Ib_parThis_0() Ib_parThis_0
#define Write_Ib_parThis_0(x) (Ib_parThis_0 = x)
#define Write0_Ib_parThis_0() (Ib_parThis_0 = 0)
#define Write1_Ib_parThis_0() (Ib_parThis_0 = 1)

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XS1() digitalRead(pin_Ub_XS1)
  #else
    PROTO(ldBOOL Read_Ub_XS1(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_once_0_ONE_SHOT_RISING;
#endif
#define Read_Ib_once_0_ONE_SHOT_RISING() Ib_once_0_ONE_SHOT_RISING
#define Write_Ib_once_0_ONE_SHOT_RISING(x) (Ib_once_0_ONE_SHOT_RISING = x)
#define Write0_Ib_once_0_ONE_SHOT_RISING() (Ib_once_0_ONE_SHOT_RISING = 0)
#define Write1_Ib_once_0_ONE_SHOT_RISING() (Ib_once_0_ONE_SHOT_RISING = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR11;
#endif
#define Read_Ub_RIR11() Ub_RIR11
#define Write_Ub_RIR11(x) (Ub_RIR11 = x)
#define Write0_Ub_RIR11() (Ub_RIR11 = 0)
#define Write1_Ub_RIR11() (Ub_RIR11 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR12;
#endif
#define Read_Ub_RIR12() Ub_RIR12
#define Write_Ub_RIR12(x) (Ub_RIR12 = x)
#define Write0_Ub_RIR12() (Ub_RIR12 = 0)
#define Write1_Ub_RIR12() (Ub_RIR12 = 1)

#ifdef EXTERN_EVERYTHING
  extern SWORD Ui_T1;
#endif
#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR1() digitalRead(pin_Ub_YR1)
    #define Write0_Ub_YR1() digitalWrite(pin_Ub_YR1, LOW)
    #define Write1_Ub_YR1() digitalWrite(pin_Ub_YR1, HIGH)
    #define Write_Ub_YR1(b) (b) ? Write1_Ub_YR1() : Write0_Ub_YR1()
  #else
    PROTO(ldBOOL Read_Ub_YR1(void));
    PROTO(void Write_Ub_YR1(ldBOOL b));
    PROTO(void Write1_Ub_YR1(void));
    PROTO(void Write0_Ub_YR1(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR2() digitalRead(pin_Ub_YR2)
    #define Write0_Ub_YR2() digitalWrite(pin_Ub_YR2, LOW)
    #define Write1_Ub_YR2() digitalWrite(pin_Ub_YR2, HIGH)
    #define Write_Ub_YR2(b) (b) ? Write1_Ub_YR2() : Write0_Ub_YR2()
  #else
    PROTO(ldBOOL Read_Ub_YR2(void));
    PROTO(void Write_Ub_YR2(ldBOOL b));
    PROTO(void Write1_Ub_YR2(void));
    PROTO(void Write0_Ub_YR2(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XPB2() digitalRead(pin_Ub_XPB2)
  #else
    PROTO(ldBOOL Read_Ub_XPB2(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parOut_1;
#endif
#define Read_Ib_parOut_1() Ib_parOut_1
#define Write_Ib_parOut_1(x) (Ib_parOut_1 = x)
#define Write0_Ib_parOut_1() (Ib_parOut_1 = 0)
#define Write1_Ib_parOut_1() (Ib_parOut_1 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parThis_1;
#endif
#define Read_Ib_parThis_1() Ib_parThis_1
#define Write_Ib_parThis_1(x) (Ib_parThis_1 = x)
#define Write0_Ib_parThis_1() (Ib_parThis_1 = 0)
#define Write1_Ib_parThis_1() (Ib_parThis_1 = 1)

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XS2() digitalRead(pin_Ub_XS2)
  #else
    PROTO(ldBOOL Read_Ub_XS2(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_once_1_ONE_SHOT_RISING;
#endif
#define Read_Ib_once_1_ONE_SHOT_RISING() Ib_once_1_ONE_SHOT_RISING
#define Write_Ib_once_1_ONE_SHOT_RISING(x) (Ib_once_1_ONE_SHOT_RISING = x)
#define Write0_Ib_once_1_ONE_SHOT_RISING() (Ib_once_1_ONE_SHOT_RISING = 0)
#define Write1_Ib_once_1_ONE_SHOT_RISING() (Ib_once_1_ONE_SHOT_RISING = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR21;
#endif
#define Read_Ub_RIR21() Ub_RIR21
#define Write_Ub_RIR21(x) (Ub_RIR21 = x)
#define Write0_Ub_RIR21() (Ub_RIR21 = 0)
#define Write1_Ub_RIR21() (Ub_RIR21 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR22;
#endif
#define Read_Ub_RIR22() Ub_RIR22
#define Write_Ub_RIR22(x) (Ub_RIR22 = x)
#define Write0_Ub_RIR22() (Ub_RIR22 = 0)
#define Write1_Ub_RIR22() (Ub_RIR22 = 1)

#ifdef EXTERN_EVERYTHING
  extern SWORD Ui_T2;
#endif
#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR3() digitalRead(pin_Ub_YR3)
    #define Write0_Ub_YR3() digitalWrite(pin_Ub_YR3, LOW)
    #define Write1_Ub_YR3() digitalWrite(pin_Ub_YR3, HIGH)
    #define Write_Ub_YR3(b) (b) ? Write1_Ub_YR3() : Write0_Ub_YR3()
  #else
    PROTO(ldBOOL Read_Ub_YR3(void));
    PROTO(void Write_Ub_YR3(ldBOOL b));
    PROTO(void Write1_Ub_YR3(void));
    PROTO(void Write0_Ub_YR3(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR4() digitalRead(pin_Ub_YR4)
    #define Write0_Ub_YR4() digitalWrite(pin_Ub_YR4, LOW)
    #define Write1_Ub_YR4() digitalWrite(pin_Ub_YR4, HIGH)
    #define Write_Ub_YR4(b) (b) ? Write1_Ub_YR4() : Write0_Ub_YR4()
  #else
    PROTO(ldBOOL Read_Ub_YR4(void));
    PROTO(void Write_Ub_YR4(ldBOOL b));
    PROTO(void Write1_Ub_YR4(void));
    PROTO(void Write0_Ub_YR4(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XPB3() digitalRead(pin_Ub_XPB3)
  #else
    PROTO(ldBOOL Read_Ub_XPB3(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parOut_2;
#endif
#define Read_Ib_parOut_2() Ib_parOut_2
#define Write_Ib_parOut_2(x) (Ib_parOut_2 = x)
#define Write0_Ib_parOut_2() (Ib_parOut_2 = 0)
#define Write1_Ib_parOut_2() (Ib_parOut_2 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parThis_2;
#endif
#define Read_Ib_parThis_2() Ib_parThis_2
#define Write_Ib_parThis_2(x) (Ib_parThis_2 = x)
#define Write0_Ib_parThis_2() (Ib_parThis_2 = 0)
#define Write1_Ib_parThis_2() (Ib_parThis_2 = 1)

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XS3() digitalRead(pin_Ub_XS3)
  #else
    PROTO(ldBOOL Read_Ub_XS3(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_once_2_ONE_SHOT_RISING;
#endif
#define Read_Ib_once_2_ONE_SHOT_RISING() Ib_once_2_ONE_SHOT_RISING
#define Write_Ib_once_2_ONE_SHOT_RISING(x) (Ib_once_2_ONE_SHOT_RISING = x)
#define Write0_Ib_once_2_ONE_SHOT_RISING() (Ib_once_2_ONE_SHOT_RISING = 0)
#define Write1_Ib_once_2_ONE_SHOT_RISING() (Ib_once_2_ONE_SHOT_RISING = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR31;
#endif
#define Read_Ub_RIR31() Ub_RIR31
#define Write_Ub_RIR31(x) (Ub_RIR31 = x)
#define Write0_Ub_RIR31() (Ub_RIR31 = 0)
#define Write1_Ub_RIR31() (Ub_RIR31 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR32;
#endif
#define Read_Ub_RIR32() Ub_RIR32
#define Write_Ub_RIR32(x) (Ub_RIR32 = x)
#define Write0_Ub_RIR32() (Ub_RIR32 = 0)
#define Write1_Ub_RIR32() (Ub_RIR32 = 1)

#ifdef EXTERN_EVERYTHING
  extern SWORD Ui_T3;
#endif
#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR5() digitalRead(pin_Ub_YR5)
    #define Write0_Ub_YR5() digitalWrite(pin_Ub_YR5, LOW)
    #define Write1_Ub_YR5() digitalWrite(pin_Ub_YR5, HIGH)
    #define Write_Ub_YR5(b) (b) ? Write1_Ub_YR5() : Write0_Ub_YR5()
  #else
    PROTO(ldBOOL Read_Ub_YR5(void));
    PROTO(void Write_Ub_YR5(ldBOOL b));
    PROTO(void Write1_Ub_YR5(void));
    PROTO(void Write0_Ub_YR5(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR6() digitalRead(pin_Ub_YR6)
    #define Write0_Ub_YR6() digitalWrite(pin_Ub_YR6, LOW)
    #define Write1_Ub_YR6() digitalWrite(pin_Ub_YR6, HIGH)
    #define Write_Ub_YR6(b) (b) ? Write1_Ub_YR6() : Write0_Ub_YR6()
  #else
    PROTO(ldBOOL Read_Ub_YR6(void));
    PROTO(void Write_Ub_YR6(ldBOOL b));
    PROTO(void Write1_Ub_YR6(void));
    PROTO(void Write0_Ub_YR6(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XPB4() digitalRead(pin_Ub_XPB4)
  #else
    PROTO(ldBOOL Read_Ub_XPB4(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parOut_3;
#endif
#define Read_Ib_parOut_3() Ib_parOut_3
#define Write_Ib_parOut_3(x) (Ib_parOut_3 = x)
#define Write0_Ib_parOut_3() (Ib_parOut_3 = 0)
#define Write1_Ib_parOut_3() (Ib_parOut_3 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_parThis_3;
#endif
#define Read_Ib_parThis_3() Ib_parThis_3
#define Write_Ib_parThis_3(x) (Ib_parThis_3 = x)
#define Write0_Ib_parThis_3() (Ib_parThis_3 = 0)
#define Write1_Ib_parThis_3() (Ib_parThis_3 = 1)

#ifndef NO_PROTOTYPES
  // LDmicro provide this macro or function.
  #ifdef USE_MACRO
    #define Read_Ub_XS4() digitalRead(pin_Ub_XS4)
  #else
    PROTO(ldBOOL Read_Ub_XS4(void));
  #endif
#endif

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ib_once_3_ONE_SHOT_RISING;
#endif
#define Read_Ib_once_3_ONE_SHOT_RISING() Ib_once_3_ONE_SHOT_RISING
#define Write_Ib_once_3_ONE_SHOT_RISING(x) (Ib_once_3_ONE_SHOT_RISING = x)
#define Write0_Ib_once_3_ONE_SHOT_RISING() (Ib_once_3_ONE_SHOT_RISING = 0)
#define Write1_Ib_once_3_ONE_SHOT_RISING() (Ib_once_3_ONE_SHOT_RISING = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR41;
#endif
#define Read_Ub_RIR41() Ub_RIR41
#define Write_Ub_RIR41(x) (Ub_RIR41 = x)
#define Write0_Ub_RIR41() (Ub_RIR41 = 0)
#define Write1_Ub_RIR41() (Ub_RIR41 = 1)

#ifdef EXTERN_EVERYTHING
  extern ldBOOL Ub_RIR42;
#endif
#define Read_Ub_RIR42() Ub_RIR42
#define Write_Ub_RIR42(x) (Ub_RIR42 = x)
#define Write0_Ub_RIR42() (Ub_RIR42 = 0)
#define Write1_Ub_RIR42() (Ub_RIR42 = 1)

#ifdef EXTERN_EVERYTHING
  extern SWORD Ui_T4;
#endif
#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR7() digitalRead(pin_Ub_YR7)
    #define Write0_Ub_YR7() digitalWrite(pin_Ub_YR7, LOW)
    #define Write1_Ub_YR7() digitalWrite(pin_Ub_YR7, HIGH)
    #define Write_Ub_YR7(b) (b) ? Write1_Ub_YR7() : Write0_Ub_YR7()
  #else
    PROTO(ldBOOL Read_Ub_YR7(void));
    PROTO(void Write_Ub_YR7(ldBOOL b));
    PROTO(void Write1_Ub_YR7(void));
    PROTO(void Write0_Ub_YR7(void));
  #endif
#endif

#ifndef NO_PROTOTYPES
  // LDmicro provide these macros or functions.
  #ifdef USE_MACRO
    #define Read_Ub_YR8() digitalRead(pin_Ub_YR8)
    #define Write0_Ub_YR8() digitalWrite(pin_Ub_YR8, LOW)
    #define Write1_Ub_YR8() digitalWrite(pin_Ub_YR8, HIGH)
    #define Write_Ub_YR8(b) (b) ? Write1_Ub_YR8() : Write0_Ub_YR8()
  #else
    PROTO(ldBOOL Read_Ub_YR8(void));
    PROTO(void Write_Ub_YR8(ldBOOL b));
    PROTO(void Write1_Ub_YR8(void));
    PROTO(void Write0_Ub_YR8(void));
  #endif
#endif

#endif
